### ISSUE TITLE
Question: enhancement allow for network flairs as well

### ISSUE THREAD

**Issue by mansueli** [johannchopin/stackoverflow-readme-profile#14]
### Your Question

There should be an option for generating the network flair e.g:

https://stackexchange.com/users/2516977/mansueli?tab=flair

<img src="https://stackexchange.com/users/flair/2516977.png">

**Comment by johannchopin** [comment]
Hey @mansueli👋 Thanks for the proposition.

It would be a nice improvement indeed. However the scope of this project is purely StackOverflow to avoid managing several APis and increase the architecture complexity (I can't sadly work full time on this project at the moment 😅). 

Nevertheless it is possible to fork this project and adapt it to the needs of the stackexchange API 😉
