### ISSUE TITLE
Tag proposition: tagname

### ISSUE THREAD

**Issue by robrich** [johannchopin/stackoverflow-readme-profile#15]
### Name of the tag

alltime

### Link to tag's StackOverflow insights

https://stackexchange.com/leagues/1/alltime/stackoverflow/2008-07-31/702931#702931

**Comment by johannchopin** [comment]
Hey @robrich 👋 I sadly don't have the time yet to provide a new badge for this kind of data. Moreover this data is not provided by the official SO API so it will require an additional scrapper. I would like to avoid abusing the SO site.

**Comment by robrich** [comment]
Completely makes sense.  I didn't realize that the API exposed the per-tag stats but not the overall stats.  This is a completely reasonable answer.
