### ISSUE TITLE
Bug report: C# tag doesn't work

### ISSUE THREAD

**Issue by robrich** [johannchopin/stackoverflow-readme-profile#16]
### Bug report

The page to get the tag is https://stackoverflow-readme-profile.vercel.app/tags-league/c%23/users/702931#badgePreview

The tag markdown provided here is:

```
[![user:702931's ranking for c#](https://stackoverflow-readme-profile.johannchopin.fr/tags-league-ranking/c#/702931?theme=default)](https://stackoverflow-readme-profile.vercel.app/tags-league/c#/users/702931)
```

This means the image URL is `https://stackoverflow-readme-profile.johannchopin.fr/tags-league-ranking/c#/702931?theme=default`

With a `#` in the middle, the requested url to the server becomes `https://stackoverflow-readme-profile.johannchopin.fr/tags-league-ranking/c` which obviously is incorrect.

Encoding the `#`, I tried `https://stackoverflow-readme-profile.johannchopin.fr/tags-league-ranking/c%23/702931?theme=default` which returns this error:

```
Error: The provided tag c# is not currently part of the Tags League.
```

Yet c# appears in the tag cloud at https://stackoverflow-readme-profile.vercel.app/tags-league

**Comment by johannchopin** [comment]
Hey @robrich 👋 Thanks for raising the issue that's indeed a "dummy" bug of url encoding. I will fix this one during the next week and will let you know 👌

**Comment by johannchopin** [comment]
Fixed the bug and the page: https://stackoverflow-readme-profile.vercel.app/tags-league/c%23/users/702931

Enjoy your badge 😉 
[![user:702931's ranking for c%23](https://stackoverflow-readme-profile.johannchopin.fr/tags-league-ranking/c%23/702931?theme=default)](https://stackoverflow-readme-profile.vercel.app/tags-league/c%23/users/702931)

If you like this project don't hesitate to leave a ⭐ on the repo!

**Comment by robrich** [comment]
Woot!  It looks great.  https://github.com/robrich
