### ISSUE TITLE
Tag proposition: ethereum

### ISSUE THREAD

**Issue by dappsar** [johannchopin/stackoverflow-readme-profile#17]
### Name of the tag

ethereum

### Link to tag's StackOverflow insights

https://stackoverflow.com/tags/ethereum/topusers

**Comment by dappsar** [comment]
add ethereum tag name

**Comment by johannchopin** [comment]
Done https://stackoverflow-readme-profile.vercel.app/tags-league/ethereum/users/4421078 👍
