### ISSUE TITLE
Tag proposition: react-hooks

### ISSUE THREAD

**Issue by Danziger** [johannchopin/stackoverflow-readme-profile#19]
### Name of the tag

react-hooks

### Link to tag's StackOverflow insights

https://stackoverflow.com/tags/react-hooks/topusers

**Comment by johannchopin** [comment]
Hey @Danziger 👋 Thanks for the suggestion but `2,527` questions with the `web-audio-api` tag is not enough in my opinion to include it in the tag-league in a relevant way.

**Comment by johannchopin** [comment]
Hey @Danziger 👋  This tag get a lot of traction with `29,809` questions tagged for sure but why not just use the `react` one?

**Comment by Danziger** [comment]
I just thought having the more specific one might be helpful, but not sure what criteria you follow to add new tags.

**Comment by johannchopin** [comment]
What do you think if I had the following "validation checkbox" in the new tag issue template:

- [ ] This new tag is a known technology or a framework for a technology, not just a concept of a technology.

Does this make it clearer?
