### ISSUE TITLE
Tag proposition: html5-canvas

### ISSUE THREAD

**Issue by Danziger** [johannchopin/stackoverflow-readme-profile#20]
### Name of the tag

html5-canvas

### Link to tag's StackOverflow insights

https://stackoverflow.com/tags/html5-canvas/topusers

**Comment by johannchopin** [comment]
Hey @Danziger 👋 Thanks for the suggestion but `12,129` questions with the `html5-canvas` tag is not enough in my opinion to include it in the tag-league in a relevant way.
