### ISSUE TITLE
Tag proposition: web-audio-api

### ISSUE THREAD

**Issue by Danziger** [johannchopin/stackoverflow-readme-profile#21]
### Name of the tag

web-audio-api

### Link to tag's StackOverflow insights

https://stackoverflow.com/tags/web-audio-api/topusers

**Comment by johannchopin** [comment]
Hey @Danziger 👋 Thanks for the suggestion but `2,527` questions with the `web-audio-api` tag is not enough in my opinion to include it in the tag-league in a relevant way.
