### ISSUE TITLE
Tag proposition: github

### ISSUE THREAD

**Issue by ImBIOS** [johannchopin/stackoverflow-readme-profile#22]
### Name of the tag

github

### Link to tag's StackOverflow insights

https://stackoverflow.com/questions/tagged/github

**Comment by johannchopin** [comment]
Hey @ImBIOS 👋 Sounds good would you like to add it to https://github.com/johannchopin/stackoverflow-readme-profile/blob/main/src/tags-league/TAGS.json and open a PR?

**Comment by johannchopin** [comment]
@ImBIOS The tag is live https://stackoverflow-readme-profile.vercel.app/tags-league/github/users/13218717 🎉
