### ISSUE TITLE
Tag proposition: google-sheets

### ISSUE THREAD

**Issue by zdtq** [johannchopin/stackoverflow-readme-profile#24]
### Name of the tag

google-sheets

### Link to tag's StackOverflow insights

https://stackoverflow.com/tags/google-sheets/topusers

**Comment by johannchopin** [comment]
Hey @zdhmd 👋 Sounds good would you like to add it to https://github.com/johannchopin/stackoverflow-readme-profile/blob/main/src/tags-league/TAGS.json and open a PR?

**Comment by zdtq** [comment]
@johannchopin, done!

**Comment by johannchopin** [comment]
@zdhmd The computation is done and the tag is live https://stackoverflow-readme-profile.vercel.app/tags-league/google-sheets/users/17887301 😉 Feel free to leave a star ⭐  to support this project!


[![user:17887301's ranking for google-sheets](https://stackoverflow-readme-profile.johannchopin.fr/tags-league-ranking/google-sheets/17887301?theme=dark)](https://stackoverflow-readme-profile.vercel.app/tags-league/google-sheets/users/17887301)
