### ISSUE TITLE
The profile image dosn't work

### ISSUE THREAD

**Issue by shayki5** [johannchopin/stackoverflow-readme-profile#30]
### Your Question

Hi,
Thank you for your project!
I just noticed that the profile image stopped from work:
![image](https://github.com/user-attachments/assets/31ee1b5e-028a-4334-8601-cab93a1e4c03)
Can you check please?

**Comment by johannchopin** [comment]
Hey @shayki5 👋

Seems the VPS is down. I upgrade the server and start the service again 👍

**Comment by shayki5** [comment]
Thank you! still doesn't work for me :(

**Comment by johannchopin** [comment]
Hey @shayki5 Sorry for the long delay but I didn't had much time.

The profile image generator is live again but there is an issue with the tags league wich is the reason to the downtime. Stackoverflow seems to have limited the SEDE queries you can send so currently I can't compute the tags league anymore. Will post a message about that.

**Comment by johannchopin** [comment]
You can track the issue related to the tags league here: https://github.com/johannchopin/stackoverflow-readme-profile/issues/31

**Comment by shayki5** [comment]
Thank you!
